#pragma once

#include <d3d12.h>

#ifndef D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE
#define D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE \
    static_cast<D3D12_RESOURCE_STATES>(0x400000)
#endif

#ifndef D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_INPUT
#define D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_INPUT \
    static_cast<D3D12_RESOURCE_STATES>(0x800000)
#endif
