#pragma once

#include "IconsFontAwesome6.h"

// Curated aliases for editor UI. Use inline with labels, e.g. ImGui::Button(ICON_EDITOR_PLAY " Play").
// Requires ImGuiFonts::LoadEditorFonts() and fa-solid-900.ttf in assets/fonts/.

#define ICON_EDITOR_PLAY ICON_FA_PLAY
#define ICON_EDITOR_PAUSE ICON_FA_PAUSE
#define ICON_EDITOR_STOP ICON_FA_STOP
#define ICON_EDITOR_SAVE ICON_FA_FLOPPY_DISK
#define ICON_EDITOR_FOLDER ICON_FA_FOLDER
#define ICON_EDITOR_FOLDER_OPEN ICON_FA_FOLDER_OPEN
#define ICON_EDITOR_FILE ICON_FA_FILE
#define ICON_EDITOR_UNDO ICON_FA_ROTATE_LEFT
#define ICON_EDITOR_REDO ICON_FA_ROTATE_RIGHT
#define ICON_EDITOR_TRASH ICON_FA_TRASH
#define ICON_EDITOR_PLUS ICON_FA_PLUS
#define ICON_EDITOR_MINUS ICON_FA_MINUS
#define ICON_EDITOR_SEARCH ICON_FA_MAGNIFYING_GLASS
#define ICON_EDITOR_SETTINGS ICON_FA_GEAR
#define ICON_EDITOR_EYE ICON_FA_EYE
#define ICON_EDITOR_EYE_SLASH ICON_FA_EYE_SLASH
#define ICON_EDITOR_LOCK ICON_FA_LOCK
#define ICON_EDITOR_UNLOCK ICON_FA_LOCK_OPEN
#define ICON_EDITOR_MOVE ICON_FA_ARROWS_UP_DOWN_LEFT_RIGHT
#define ICON_EDITOR_ROTATE ICON_FA_ROTATE
#define ICON_EDITOR_SCALE ICON_FA_UP_RIGHT_AND_DOWN_LEFT_FROM_CENTER
#define ICON_EDITOR_CUBE ICON_FA_CUBE
#define ICON_EDITOR_SPHERE ICON_FA_CIRCLE
#define ICON_EDITOR_CAMERA ICON_FA_CAMERA
#define ICON_EDITOR_LIGHT ICON_FA_LIGHTBULB
#define ICON_EDITOR_SUN ICON_FA_SUN
#define ICON_EDITOR_GRID ICON_FA_BORDER_ALL
#define ICON_EDITOR_MATERIAL ICON_FA_PALETTE
#define ICON_EDITOR_PHYSICS ICON_FA_WEIGHT_HANGING
#define ICON_EDITOR_COLLIDER ICON_FA_DRAW_POLYGON
#define ICON_EDITOR_HIERARCHY ICON_FA_SITEMAP
#define ICON_EDITOR_INSPECTOR ICON_FA_LIST
#define ICON_EDITOR_WARNING ICON_FA_TRIANGLE_EXCLAMATION
#define ICON_EDITOR_INFO ICON_FA_CIRCLE_INFO
